import type { DomainId, Section, Skill, Unit } from "./types"

export const DOMAINS: Record<
  DomainId,
  { section: Section; title: string; officialNote: string }
> = {
  "information-ideas": {
    section: "rw",
    title: "Information and Ideas",
    officialNote:
      "Official Reading and Writing domain covering evidence, inference, and central meaning. Anannt units RW0–RW4 teach this domain.",
  },
  "craft-structure": {
    section: "rw",
    title: "Craft and Structure",
    officialNote:
      "Official Reading and Writing domain covering words in context, text structure, purpose, and related texts. Anannt units RW5–RW7 teach this domain.",
  },
  "expression-of-ideas": {
    section: "rw",
    title: "Expression of Ideas",
    officialNote:
      "Official Reading and Writing domain covering rhetorical revision and synthesis. Anannt units RW10–RW12 teach this domain, with mixed application in RW12.",
  },
  "standard-english-conventions": {
    section: "rw",
    title: "Standard English Conventions",
    officialNote:
      "Official Reading and Writing domain covering sentence boundaries, form, and usage. Anannt units RW8–RW9 teach this domain.",
  },
  algebra: {
    section: "math",
    title: "Algebra",
    officialNote:
      "Official Math domain covering linear relationships. Anannt units M1–M3 teach this domain, with numerical foundations in M0.",
  },
  "advanced-math": {
    section: "math",
    title: "Advanced Math",
    officialNote:
      "Official Math domain covering nonlinear expressions, equations, and functions. Anannt units M4–M6 teach this domain.",
  },
  "problem-solving-data-analysis": {
    section: "math",
    title: "Problem-Solving and Data Analysis",
    officialNote:
      "Official Math domain covering quantitative reasoning and statistics. Anannt units M7–M11 teach this domain.",
  },
  "geometry-trigonometry": {
    section: "math",
    title: "Geometry and Trigonometry",
    officialNote:
      "Official Math domain covering spatial measurement and right-triangle reasoning. Anannt units M12–M13 teach this domain, with tools in M14.",
  },
}

export const UNITS: Unit[] = [
  {
    id: "RW0",
    section: "rw",
    domain: "information-ideas",
    order: 0,
    title: "Reading foundations",
    shortTitle: "Foundations",
    coverage:
      "Separate claims from examples; paraphrase sentences; identify clause roles; follow logical relationships.",
    evidence: "State what a sentence means without copying it.",
    prerequisites: [],
    lessonIds: ["RW0-L1"],
  },
  {
    id: "RW1",
    section: "rw",
    domain: "information-ideas",
    order: 1,
    title: "Central meaning",
    shortTitle: "Central meaning",
    coverage: "Main claim, supporting detail, scope and relevance.",
    evidence: "Choose a summary and identify its textual support.",
    prerequisites: ["RW0"],
    lessonIds: ["RW1-L1"],
  },
  {
    id: "RW2",
    section: "rw",
    domain: "information-ideas",
    order: 2,
    title: "Textual evidence",
    shortTitle: "Evidence",
    coverage: "Match evidence to a claim; distinguish support from contradiction.",
    evidence: "Reject a plausible but irrelevant quotation.",
    prerequisites: ["RW1"],
    lessonIds: ["RW2-L1"],
  },
  {
    id: "RW3",
    section: "rw",
    domain: "information-ideas",
    order: 3,
    title: "Quantitative evidence",
    shortTitle: "Data in text",
    coverage: "Read axes, units and trends; connect a graph to a claim.",
    evidence: "Select a conclusion consistent with both text and data.",
    prerequisites: ["RW2"],
    lessonIds: ["RW3-L1"],
  },
  {
    id: "RW4",
    section: "rw",
    domain: "information-ideas",
    order: 4,
    title: "Inference",
    shortTitle: "Inference",
    coverage: "Necessary implications, cautious conclusions and scope limits.",
    evidence: "Explain why an attractive answer goes beyond the text.",
    prerequisites: ["RW1", "RW2"],
    lessonIds: ["RW4-L1"],
  },
  {
    id: "RW5",
    section: "rw",
    domain: "craft-structure",
    order: 5,
    title: "Words in context",
    shortTitle: "Words in context",
    coverage: "Use sentence logic, contrast and tone to infer meaning.",
    evidence: "Transfer a word to a new context; avoid memorized-definition traps.",
    prerequisites: ["RW0"],
    lessonIds: ["RW5-L1"],
  },
  {
    id: "RW6",
    section: "rw",
    domain: "craft-structure",
    order: 6,
    title: "Structure and purpose",
    shortTitle: "Structure",
    coverage: "Identify a sentence's role and the author's purpose.",
    evidence: "Explain how a detail develops the passage.",
    prerequisites: ["RW1"],
    lessonIds: ["RW6-L1"],
  },
  {
    id: "RW7",
    section: "rw",
    domain: "craft-structure",
    order: 7,
    title: "Related texts",
    shortTitle: "Paired texts",
    coverage: "Compare positions, agreement and qualifications.",
    evidence: "Identify how one author would respond to the other.",
    prerequisites: ["RW4"],
    lessonIds: ["RW7-L1"],
  },
  {
    id: "RW8",
    section: "rw",
    domain: "standard-english-conventions",
    order: 8,
    title: "Sentence boundaries",
    shortTitle: "Boundaries",
    coverage: "Clauses, fragments, run-ons and punctuation between complete ideas.",
    evidence: "Edit a boundary and justify the clause relationship.",
    prerequisites: ["RW0"],
    lessonIds: ["RW8-L1"],
  },
  {
    id: "RW9",
    section: "rw",
    domain: "standard-english-conventions",
    order: 9,
    title: "Form and usage",
    shortTitle: "Usage",
    coverage: "Agreement, verb consistency, pronoun clarity and modifier placement.",
    evidence: "Locate the governing grammatical relationship.",
    prerequisites: ["RW8"],
    lessonIds: ["RW9-L1"],
  },
  {
    id: "RW10",
    section: "rw",
    domain: "expression-of-ideas",
    order: 10,
    title: "Connections",
    shortTitle: "Transitions",
    coverage: "Choose transitions from the actual logical relationship.",
    evidence: "Describe the connection before viewing options.",
    prerequisites: ["RW1"],
    lessonIds: ["RW10-L1"],
  },
  {
    id: "RW11",
    section: "rw",
    domain: "expression-of-ideas",
    order: 11,
    title: "Rhetorical synthesis",
    shortTitle: "Synthesis",
    coverage: "Select relevant notes for a stated communication goal.",
    evidence: "Produce a concise answer that satisfies the goal.",
    prerequisites: ["RW2"],
    lessonIds: ["RW11-L1"],
  },
  {
    id: "RW12",
    section: "rw",
    domain: "expression-of-ideas",
    order: 12,
    title: "Mixed application",
    shortTitle: "Mixed RW",
    coverage: "Switch among reading, editing and synthesis tasks.",
    evidence: "Maintain accuracy on unseen mixed sets.",
    prerequisites: ["RW4", "RW8", "RW11"],
    lessonIds: ["RW12-L1"],
  },
  {
    id: "M0",
    section: "math",
    domain: "algebra",
    order: 20,
    title: "Numerical foundations",
    shortTitle: "Number sense",
    coverage:
      "Fractions, decimals, signed numbers, order of operations and proportional reasoning.",
    evidence: "Explain operations and preserve equivalent quantities.",
    prerequisites: [],
    lessonIds: ["M0-L1"],
  },
  {
    id: "M1",
    section: "math",
    domain: "algebra",
    order: 21,
    title: "Linear equations",
    shortTitle: "Linear equations",
    coverage: "One-variable equations, translating statements and parameter interpretation.",
    evidence: "Solve and explain the meaning of the answer.",
    prerequisites: ["M0"],
    lessonIds: ["M1-L1"],
  },
  {
    id: "M2",
    section: "math",
    domain: "algebra",
    order: 22,
    title: "Linear representations",
    shortTitle: "Slope & graphs",
    coverage: "Slope, intercept, tables, graphs and functions.",
    evidence: "Move accurately between representations.",
    prerequisites: ["M1"],
    lessonIds: ["M2-L1"],
  },
  {
    id: "M3",
    section: "math",
    domain: "algebra",
    order: 23,
    title: "Systems and inequalities",
    shortTitle: "Systems",
    coverage: "Simultaneous relationships, feasible solutions and inequality graphs.",
    evidence: "Check a solution against all constraints.",
    prerequisites: ["M2"],
    lessonIds: ["M3-L1"],
  },
  {
    id: "M4",
    section: "math",
    domain: "advanced-math",
    order: 24,
    title: "Expression structure",
    shortTitle: "Expressions",
    coverage: "Exponents, factoring, radicals and equivalent forms.",
    evidence: "Choose a useful form and identify domain restrictions.",
    prerequisites: ["M0"],
    lessonIds: ["M4-L1"],
  },
  {
    id: "M5",
    section: "math",
    domain: "advanced-math",
    order: 25,
    title: "Nonlinear equations",
    shortTitle: "Nonlinear",
    coverage: "Quadratics and other permitted nonlinear equations and systems.",
    evidence: "Solve and reject invalid or extraneous results.",
    prerequisites: ["M4", "M1"],
    lessonIds: ["M5-L1"],
  },
  {
    id: "M6",
    section: "math",
    domain: "advanced-math",
    order: 26,
    title: "Nonlinear functions",
    shortTitle: "Functions",
    coverage: "Function features, growth, transformations and model interpretation.",
    evidence: "Interpret parameters and compare models.",
    prerequisites: ["M5", "M2"],
    lessonIds: ["M6-L1"],
  },
  {
    id: "M7",
    section: "math",
    domain: "problem-solving-data-analysis",
    order: 27,
    title: "Ratios and units",
    shortTitle: "Ratios",
    coverage: "Rates, conversions, proportional models and percentages.",
    evidence: "Keep units consistent through a multistep solution.",
    prerequisites: ["M0"],
    lessonIds: ["M7-L1"],
  },
  {
    id: "M8",
    section: "math",
    domain: "problem-solving-data-analysis",
    order: 28,
    title: "One-variable data",
    shortTitle: "One-variable data",
    coverage: "Distribution shape, center, variability and effects of changes.",
    evidence: "Explain how a changed observation affects a summary.",
    prerequisites: ["M0"],
    lessonIds: ["M8-L1"],
  },
  {
    id: "M9",
    section: "math",
    domain: "problem-solving-data-analysis",
    order: 29,
    title: "Two-variable data",
    shortTitle: "Scatterplots",
    coverage: "Scatterplots, fitted relationships and prediction.",
    evidence: "Interpret a model within a reasonable range.",
    prerequisites: ["M2", "M8"],
    lessonIds: ["M9-L1"],
  },
  {
    id: "M10",
    section: "math",
    domain: "problem-solving-data-analysis",
    order: 30,
    title: "Probability",
    shortTitle: "Probability",
    coverage: "Sample spaces, conditional reasoning and two-way tables.",
    evidence: "Identify the correct denominator.",
    prerequisites: ["M7"],
    lessonIds: ["M10-L1"],
  },
  {
    id: "M11",
    section: "math",
    domain: "problem-solving-data-analysis",
    order: 31,
    title: "Statistical reasoning",
    shortTitle: "Stats claims",
    coverage: "Sampling, uncertainty, study design and statistical claims.",
    evidence: "Distinguish evidence for association from causation.",
    prerequisites: ["M8"],
    lessonIds: ["M11-L1"],
  },
  {
    id: "M12",
    section: "math",
    domain: "geometry-trigonometry",
    order: 32,
    title: "Geometry",
    shortTitle: "Geometry",
    coverage: "Measurement, angles, triangles, circles, area and volume.",
    evidence: "Build a diagram and select relevant relationships.",
    prerequisites: ["M0"],
    lessonIds: ["M12-L1"],
  },
  {
    id: "M13",
    section: "math",
    domain: "geometry-trigonometry",
    order: 33,
    title: "Right-triangle reasoning",
    shortTitle: "Right triangles",
    coverage: "Similarity, Pythagorean relationships and permitted trigonometry.",
    evidence: "Choose a relationship from given information.",
    prerequisites: ["M12"],
    lessonIds: ["M13-L1"],
  },
  {
    id: "M14",
    section: "math",
    domain: "geometry-trigonometry",
    order: 34,
    title: "Tools and transfer",
    shortTitle: "Tools",
    coverage: "Graphing calculator, numeric response entry, estimation and mixed applications.",
    evidence: "Choose an efficient method and verify plausibility.",
    prerequisites: ["M5", "M7", "M12"],
    lessonIds: ["M14-L1"],
  },
]

export const SKILLS: Skill[] = UNITS.map((unit) => ({
  id: `${unit.id}-S1`,
  unitId: unit.id,
  title: unit.title,
  domain: unit.domain,
  section: unit.section,
  highRelevance: ["RW1", "RW2", "RW8", "M1", "M2", "M7"].includes(unit.id),
}))

export function unitById(id: string) {
  return UNITS.find((u) => u.id === id)
}

export function skillByUnit(unitId: string) {
  return SKILLS.find((s) => s.unitId === unitId)
}

export function skillById(id: string) {
  return SKILLS.find((s) => s.id === id)
}

export const OFFICIAL_STRUCTURE = {
  rwModules: { questions: 27, minutes: 32 },
  mathModules: { questions: 22, minutes: 35 },
  totalQuestions: 98,
  totalMinutes: 134,
  breakMinutes: 10,
  scoreScale: { total: "320–1520", section: "160–760" },
  sources: [
    {
      label: "PSAT/NMSQT structure",
      href: "https://satsuite.collegeboard.org/in-school-assessments/whats-on-the-test/psat-nmsqt/structure",
    },
    {
      label: "Digital SAT Suite specifications",
      href: "https://satsuite.collegeboard.org/media/pdf/digital-sat-test-spec-overview.pdf",
    },
    {
      label: "PSAT/NMSQT Student Guide",
      href: "https://satsuite.collegeboard.org/media/pdf/psat-nmsqt-student-guide.pdf",
    },
    {
      label: "Bluebook practice",
      href: "https://bluebook.collegeboard.org/students/practice",
    },
  ],
}

export const MASTERY_LABELS: Record<
  import("./types").MasteryState,
  { title: string; hint: string }
> = {
  unknown: {
    title: "Unknown",
    hint: "Not enough independent evidence yet.",
  },
  learning: {
    title: "Learning",
    hint: "Instruction started, or a prerequisite still needs support.",
  },
  practising: {
    title: "Practising",
    hint: "Independent evidence exists but is still inconsistent.",
  },
  "provisionally-secure": {
    title: "Provisionally secure",
    hint: "At least 10 first-attempt, unhinted responses across two sessions, 80%+ correct, more than one item family.",
  },
  retained: {
    title: "Retained",
    hint: "A later check at least seven days after provisional mastery reached at least 4/5 on fresh items.",
  },
  "needs-refresh": {
    title: "Needs refresh",
    hint: "A later check or repeated misconception contradicts earlier evidence.",
  },
}
